### ISSUE TITLE
SyntaxError: Identifier 'attachment' has already been declared

### ISSUE THREAD

**Issue by opti21** [instafluff/ComfyDiscord#4]
I tried running my app today and it gave off this error for ComfyDiscord

```
const attachment = new Discord.Attachment( attachment, filename );
      ^

SyntaxError: Identifier 'attachment' has already been declared
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/browe/Documents/dev/vibey_bot/server.js:20:22)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by instafluff** [comment]
Fixed with 7e772963e0f62049ffdb3f951a3601c5bfbedabe !
